sprint-1/step-1
movsumlu/BurgerApp pull request #1
Opened 2023-10-23 11:03 UTC by movsumlu

2023-10-24 16:13 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Хорошая декомпоизция компонентов
- Логичный и понятный код

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В проекте много скроллов у контейнеров - желательно их убрать. В списке ингредиентов в одной строке должны отображаться сразу два ингредиента - пожалуйста свертесь с дизайном. Так же ограничьте высоту контейнеров с контентом, чтобы они не уходили далеко вниз за пределы видимой части страницы. 

<img width="846" alt="image" src="https://github.com/movsumlu/BurgerApp/assets/60173362/127bb4df-fb74-45db-8e07-d0221f0168c9">

- Использовать атрибут `style` следует только для динамических стилей, во всех остальных случаях следует использовать классовые стили

- Если вы используете typescript то как минимум массив объектов ингредиентов необходимо типизировать, а не использовать `any` 

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-24 16:13 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +        <Tab
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2023-10-25 13:14 UTC, movsumlu commented
добрый вечер,
- добавил ограничение по высоте для контейнера c ингридиентами
- добавил стилизованный, вертикальный скролл, убрал горизонтальный скролл
- убрал из проекта `any`, добавил типизацию через typescript-интерфейсы
- убрал аттрибуты style в проекте, перенес в css-классы

2023-10-26 08:07 UTC, andryxxa93 commented
Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы. Удачи!

2023-10-26 08:13 UTC, merged