sprint-1/step-2 / add scrolling by ingredients element by click on na…
movsumlu/BurgerApp pull request #2
Opened 2023-10-26 09:55 UTC by movsumlu

…v, update css-styles for ingredientsBlockItem

2023-10-26 17:52 UTC, andryxxa93 requested changes
**Необходимо исправить**
- На данном этапе работы необходимо делать запрос на сервер и настроить отображение модальных окон. Пожалуйста обратите ещё раз внимание на тех-задание

2023-10-29 07:31 UTC, andryxxa93 requested changes
Необходимо исправить:
- Все элементы в конструкторе должны быть одинаковой ширины

<img width="423" alt="image" src="https://github.com/movsumlu/BurgerApp/assets/60173362/d018c05d-1126-4786-9e4f-2552572c2e48">

 - Добавьте проверку ответа сервера - res.ok (подробнее смотрите комментарий к pull-request)
 
 - Для отображения модалки нужно использовать `createPortal`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-29 07:31 UTC, andryxxa93 commented on src/components/app/index.tsx
> +    fetch(`${apiURL}/api/ingredients`)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-10-29 07:31 UTC, andryxxa93 commented on src/components/app/index.tsx
> +      .then((response) => response.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-10-29 07:31 UTC, andryxxa93 commented on src/components/app/index.tsx
> +      .catch((error) => console.error(error));
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-10-29 07:31 UTC, andryxxa93 commented on src/components/burger-ingredients/index.tsx
> +  const mains = ingredients.filter(({ type }) => type === "main");
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-10-29 08:19 UTC, movsumlu commented
спасибо за обратную связь,
- сделал отображение `Modal` через `ReactDOM.createPortal`
- добавил хук `useMemo` в фильтрации ингредиентов
- добавил проверку на `response.ok` в отправке запроса, p.s. попозже вынесу в utils
- добавил ширину для `. burgerConstructorElement`

2023-10-29 20:34 UTC, andryxxa93 commented
Супер, вы отлично поработали!

**Можно лучше**
- Булки не должны скролиться, должен скролиться только контент между ними.

Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-30 06:40 UTC, merged