sprint-2 / step-2
movsumlu/BurgerApp pull request #4
Opened 2023-11-04 18:43 UTC by movsumlu

…hes to ./src, mirror updates

2023-11-09 14:29 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/fygERFgapIwSRA> - кажется, тут должен быть другой фон;

- Нужно поправить работу c DnD, у вас немного неправильно работает алгоритм. <https://disk.yandex.com/i/2lrYHWS0bZY0Ow> - экшен должен вызываться единожды при смене позиции элемента, а не пока пользователь держит элемент мышкой и находится в пределах его блока. Советую обратиться за помощью к наставнику.

- В компоненте App-header иконка и текст должны быть обёрнуты в ссылку;

- Нужно запретить нажатие кнопки, если пользователь выбрал только ингредиенты <https://disk.yandex.com/i/TTLqoK6LzNQ8iA>;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-11-09 14:29 UTC, ArslanMustafin commented on src/components/burger-constructor-item/index.tsx
> +    },
**Надо исправить:**

Сейчас у вас немного неправильно работает DnD, вам не хватает условий.

Вот правильный пример: 

```js
 hover(item, monitor) {
    const dragIndex = item.index;
    const hoverIndex = index;
   
   // Если ингредиент находиться на своей позиции.
    if (dragIndex === hoverIndex) {
      return;
    }
    
    // получаем различные данные расположения
    const hoverBoundingRect = ref.current?.getBoundingClientRect();
    const hoverMiddleY =
      (hoverBoundingRect.bottom - hoverBoundingRect.top) / 2;
    const clientOffset = monitor.getClientOffset();
    const hoverClientY = clientOffset.y - hoverBoundingRect.top;
    
    // проверяем что ингредиенты не выходит за рамки своего блока
    if (dragIndex < hoverIndex && hoverClientY < hoverMiddleY) {
      return;
    }
    if (dragIndex > hoverIndex && hoverClientY > hoverMiddleY) {
      return;
    }

    // Если ингредиент покинул свой блок, то мы соответственно меняем ему расположение.
    dispatch({
      type: CONSTRUCTOR_REORDER,
      payload: {
        from: dragIndex,
        to: hoverIndex,
      },
    });
    item.index = hoverIndex;
  },
```

2023-11-09 14:29 UTC, ArslanMustafin commented on src/components/burger-constructor/index.tsx
> +      if (ingredient[0].type === "bun") {
**Надо исправить:**

Почему бы сразу не передавать цельный объект, а не массив?

2023-11-09 14:29 UTC, ArslanMustafin commented on src/components/burger-constructor/index.tsx
> +      } else if (ingredient[0].type !== "bun") {
**Надо исправить:**

Не думаю что тут нужно дополнительно писать условие, т.к. тип в любом случае будет не `bun`. 
Можно просто написать так:

```js
if (ingredient[0].type === 'bun') {
  dispatch(addBuns(ingredient));
  return;
}
dispatch(addIngredient(ingredient));

```

2023-11-09 14:29 UTC, ArslanMustafin commented on src/store/modal/slice.ts
> +};
**Надо исправить:**

не стоит делать отдельный редьюсер для модального окна. 

Нужно вынести отдельно такие вещи как:
 
- открытие ингредиента в попапе
- оформление заказа
  
Это всё-таки разные сущности, и немного неправильно их объединять в `modal`.

А также, не стоит хранить какие-либо данные о модальном окне, это лучше делать в локальном стейте (в компоненте), а не в глобальном.

2023-11-09 14:29 UTC, ArslanMustafin commented on src/store/orderList/slice.ts
> +  orderList: [],
**Можно лучше:**

Лучше разделить булку и ингредиенты, и станет намного проще работать с данными.

2023-11-09 14:29 UTC, ArslanMustafin commented on src/store/orderList/slice.ts
> +      let updatedOrderList = [...state.orderList];
**Надо исправить:**

Здесь и далее. 

Тут нужно использовать `const`, а не `let`. Массив это ссылочный тип данных.

2023-11-09 14:29 UTC, ArslanMustafin commented on src/utils/burger-API.ts
> +export const apiURL = "https://norma.nomoreparties.space";
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`

2023-11-10 11:35 UTC, movsumlu commented
исправил:
- обернул текст и иконку в `header` в тег ссылки - `<a />`
- заменил все `let` на `const`
- доработал логику отображения кнопки "Оформить заказ", если в заказе только ингредиенты, то состояние кнопки - `disabled`
- удалил `modalSlice`, перенес отображение модального окна заказа и ингредиента в соответствующие slice-ы
- доработал `drag&drop` ингредиента в `orderList`
- переименовал константы в upper-case

2023-11-10 17:28 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- Теперь у вас можно перетаскивать булки <https://disk.yandex.com/i/9ipVUN9hny4Ptw>, по заданию булки должны оставаться на месте, только ингредиенты могут менять свою очередность.

- Только первая ссылка должна иметь белый цвет - <https://disk.yandex.com/i/j2ctxNrMfxbWOg>;

### **Сделает код лучше:**

- <https://disk.yandex.com/i/fygERFgapIwSRA> - кажется, у модального окна должен быть другой фон. Правильный цвет фона: `#1C1C21`, ну и обводку тоже нужно убрать;

- Объясню почему следует разделять экшены по файлам. У нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктора. Лучше, чтобы экшены относящиеся к решению каждой задачи, были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавляться новый функционал. И плохо, если придется все экшены описывать в одном файле, он будет слишком большой.

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

  Это оптимальный вариант)

2023-11-11 06:13 UTC, movsumlu commented
исправил замечания:
- первая ссылка имеет белый цвет в `header`
- убрал обводку модального окна и установил правильный цвет `background`

насчет замечания про то что можно перетаскивать булки, видимо проверка началось перед последним мои коммитом, добавлял дополнительную првоерку что нельзя перетаскивать булки и на другие ингридиенты нельзя перетаскивать на место булки:
```
if (
  ingredient.item.type !== "bun" &&
  orderList[hoverIndex].type !== "bun"
) {
  dispatch(replaceIngredient({ dragIndex, hoverIndex }));
}
```

2023-11-11 07:36 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-11-11 07:41 UTC, ArslanMustafin commented
> исправил замечания:
> 
> * первая ссылка имеет белый цвет в `header`
> * убрал обводку модального окна и установил правильный цвет `background`
> 
> насчет замечания про то что можно перетаскивать булки, видимо проверка началось перед последним мои коммитом, добавлял дополнительную првоерку что нельзя перетаскивать булки и на другие ингридиенты нельзя перетаскивать на место булки:
> 
> ```
> if (
>   ingredient.item.type !== "bun" &&
>   orderList[hoverIndex].type !== "bun"
> ) {
>   dispatch(replaceIngredient({ dragIndex, hoverIndex }));
> }
> ```

Видимо да. В идеале булки вообще не должны иметь DnD в конструкторе)), но если они не меняют своё расположение, то думаю окей. Но лучше вынесите булки в отдельный компонент, или можете просто написать так:

```js
{bun && (
  <div
    className={`${styles.element} mb-4 mr-4`}
  >
    <ConstructorElement
      type="top"
      isLocked={true}
      text={`${bun.name} (верх)`}
      price={bun.price}
      thumbnail={bun.image}
    />
  </div>
)}
 // ... список ингредиентов
{bun && (
  <div
    className={`${styles.element} mb-4 mr-4`}
  >
    <ConstructorElement
      type="bottom"
      isLocked={true}
      text={`${bun.name} (низ)`}
      price={bun.price}
      thumbnail={bun.image}
    />
  </div>
)}
``` 

Тогда по идее вам проверки никакие не нужны, и булки будут оставаться на месте.

2023-11-11 09:51 UTC, merged